namespace Hmsnet.Api.Thrift;

// ─────────────────────────────────────────────────────────────────────────────
// Plain C# representations of the Hive Metastore Thrift structs.
// In a full implementation these would be auto-generated by the Thrift compiler
// from hive_metastore.thrift.  We keep them lightweight here so the handler
// and processor compile without the generated code being checked in.
// ─────────────────────────────────────────────────────────────────────────────

public record ThriftFieldSchema(string Name, string Type, string? Comment);

public record ThriftSerDeInfo(string? Name, string SerializationLib, Dictionary<string, string>? Parameters);

public record ThriftOrder(string Col, int Order);

public record ThriftStorageDescriptor(
    string Location,
    string InputFormat,
    string OutputFormat,
    bool Compressed,
    int NumBuckets,
    ThriftSerDeInfo SerDeInfo,
    List<string>? BucketCols,
    List<ThriftOrder>? SortCols,
    Dictionary<string, string>? Parameters,
    List<ThriftFieldSchema>? Cols = null);

public record ThriftDatabase(
    string Name,
    string? Description,
    string LocationUri,
    string? OwnerName,
    Dictionary<string, string>? Parameters);

public class ThriftTable
{
    public string TableName { get; init; } = string.Empty;
    public string DbName { get; init; } = string.Empty;
    public string? Owner { get; init; }
    public string TableType { get; init; } = "MANAGED_TABLE";
    public int CreateTime { get; init; }
    public int LastAccessTime { get; init; }
    public int Retention { get; init; }
    public ThriftStorageDescriptor? Sd { get; init; }
    public List<ThriftFieldSchema>? Columns { get; init; }
    public List<ThriftFieldSchema>? PartitionKeys { get; init; }
    public string? ViewOriginalText { get; init; }
    public string? ViewExpandedText { get; init; }
    public Dictionary<string, string>? Parameters { get; init; }

    public ThriftTable() { }

    public ThriftTable(string tableName, string dbName, string? owner, string tableType,
        int createTime, int lastAccessTime, int retention,
        ThriftStorageDescriptor? sd,
        List<ThriftFieldSchema>? columns, List<ThriftFieldSchema>? partitionKeys,
        string? viewOriginalText, string? viewExpandedText,
        Dictionary<string, string>? parameters)
    {
        TableName = tableName; DbName = dbName; Owner = owner; TableType = tableType;
        CreateTime = createTime; LastAccessTime = lastAccessTime; Retention = retention;
        Sd = sd; Columns = columns; PartitionKeys = partitionKeys;
        ViewOriginalText = viewOriginalText; ViewExpandedText = viewExpandedText;
        Parameters = parameters;
    }
}

public class ThriftPartition
{
    public List<string>? Values { get; set; }
    public string DbName { get; set; } = string.Empty;
    public string TableName { get; set; } = string.Empty;
    public int CreateTime { get; set; }
    public int LastAccessTime { get; set; }
    public ThriftStorageDescriptor? Sd { get; set; }
    public Dictionary<string, string>? Parameters { get; set; }

    public ThriftPartition() { }

    public ThriftPartition(List<string>? values, string dbName, string tableName,
        int createTime, int lastAccessTime, ThriftStorageDescriptor? sd,
        Dictionary<string, string>? parameters)
    {
        Values = values; DbName = dbName; TableName = tableName;
        CreateTime = createTime; LastAccessTime = lastAccessTime;
        Sd = sd; Parameters = parameters;
    }
}
