// <auto-generated />
using Hmsnet.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hmsnet.Infrastructure.Migrations
{
    [DbContext(typeof(MetastoreDbContext))]
    [Migration("20260328090230_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hmsnet.Core.Models.ColumnStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AvgColLen")
                        .HasColumnType("double precision");

                    b.Property<string>("BitVector")
                        .HasColumnType("text");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ColumnType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long?>("DateHigh")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateLow")
                        .HasColumnType("bigint");

                    b.Property<string>("DecimalHigh")
                        .HasColumnType("text");

                    b.Property<string>("DecimalLow")
                        .HasColumnType("text");

                    b.Property<double?>("DoubleHigh")
                        .HasColumnType("double precision");

                    b.Property<double?>("DoubleLow")
                        .HasColumnType("double precision");

                    b.Property<long>("LastAnalyzed")
                        .HasColumnType("bigint");

                    b.Property<long?>("LongHigh")
                        .HasColumnType("bigint");

                    b.Property<long?>("LongLow")
                        .HasColumnType("bigint");

                    b.Property<long?>("MaxColLen")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumDistinctValues")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumFalses")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumNulls")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumTrues")
                        .HasColumnType("bigint");

                    b.Property<int?>("PartitionId")
                        .HasColumnType("integer");

                    b.Property<int>("StatisticsType")
                        .HasColumnType("integer");

                    b.Property<int?>("TableId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartitionId");

                    b.HasIndex("TableId");

                    b.ToTable("ColumnStatistics");
                });

            modelBuilder.Entity("Hmsnet.Core.Models.HiveColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<bool>("IsPartitionKey")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("OrdinalPosition")
                        .HasColumnType("integer");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("Hmsnet.Core.Models.HiveDatabase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LocationUri")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Databases");
                });

            modelBuilder.Entity("Hmsnet.Core.Models.HivePartition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint");

                    b.Property<long>("LastAccessTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StorageDescriptorId")
                        .HasColumnType("integer");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.Property<string>("ValuesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Values");

                    b.HasKey("Id");

                    b.HasIndex("StorageDescriptorId")
                        .IsUnique();

                    b.HasIndex("TableId");

                    b.ToTable("Partitions");
                });

            modelBuilder.Entity("Hmsnet.Core.Models.HiveTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint");

                    b.Property<int>("DatabaseId")
                        .HasColumnType("integer");

                    b.Property<long>("LastAccessTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Retention")
                        .HasColumnType("integer");

                    b.Property<bool>("RewriteEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("StorageDescriptorId")
                        .HasColumnType("integer");

                    b.Property<int>("TableType")
                        .HasColumnType("integer");

                    b.Property<bool>("Temporary")
                        .HasColumnType("boolean");

                    b.Property<string>("ViewExpandedText")
                        .HasColumnType("text");

                    b.Property<string>("ViewOriginalText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StorageDescriptorId");

                    b.HasIndex("DatabaseId", "Name")
                        .IsUnique();

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("Hmsnet.Core.Models.SerDeInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerializationLib")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("StorageDescriptorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorageDescriptorId")
                        .IsUnique();

                    b.ToTable("SerDeInfos");
                });

            modelBuilder.Entity("Hmsnet.Core.Models.StorageDescriptor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BucketColumns")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Compressed")
                        .HasColumnType("boolean");

                    b.Property<string>("InputFormat")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<int>("NumBuckets")
                        .HasColumnType("integer");

                    b.Property<string>("OutputFormat")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkewedInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SortColumns")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("StoredAsSubDirectories")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("StorageDescriptors");
                });

            modelBuilder.Entity("Hmsnet.Core.Models.ColumnStatistics", b =>
                {
                    b.HasOne("Hmsnet.Core.Models.HivePartition", "Partition")
                        .WithMany("ColumnStatistics")
                        .HasForeignKey("PartitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hmsnet.Core.Models.HiveTable", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Partition");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Hmsnet.Core.Models.HiveColumn", b =>
                {
                    b.HasOne("Hmsnet.Core.Models.HiveTable", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Hmsnet.Core.Models.HivePartition", b =>
                {
                    b.HasOne("Hmsnet.Core.Models.StorageDescriptor", "StorageDescriptor")
                        .WithOne("Partition")
                        .HasForeignKey("Hmsnet.Core.Models.HivePartition", "StorageDescriptorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hmsnet.Core.Models.HiveTable", "Table")
                        .WithMany("Partitions")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorageDescriptor");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Hmsnet.Core.Models.HiveTable", b =>
                {
                    b.HasOne("Hmsnet.Core.Models.HiveDatabase", "Database")
                        .WithMany("Tables")
                        .HasForeignKey("DatabaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hmsnet.Core.Models.StorageDescriptor", "StorageDescriptor")
                        .WithMany()
                        .HasForeignKey("StorageDescriptorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Database");

                    b.Navigation("StorageDescriptor");
                });

            modelBuilder.Entity("Hmsnet.Core.Models.SerDeInfo", b =>
                {
                    b.HasOne("Hmsnet.Core.Models.StorageDescriptor", "StorageDescriptor")
                        .WithOne("SerDeInfo")
                        .HasForeignKey("Hmsnet.Core.Models.SerDeInfo", "StorageDescriptorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorageDescriptor");
                });

            modelBuilder.Entity("Hmsnet.Core.Models.HiveDatabase", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("Hmsnet.Core.Models.HivePartition", b =>
                {
                    b.Navigation("ColumnStatistics");
                });

            modelBuilder.Entity("Hmsnet.Core.Models.HiveTable", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Partitions");
                });

            modelBuilder.Entity("Hmsnet.Core.Models.StorageDescriptor", b =>
                {
                    b.Navigation("Partition");

                    b.Navigation("SerDeInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
